### ISSUE TITLE
UI: Admin Site Maintenance Notifications

### ISSUE THREAD

**Issue by schmelz21** [cisagov/XFD#100]
# 💡 Summary #

The Admin site maintenance tool should allow administrators to manage site maintenance messages. And create a method to issue a site management page. These messages will be displayed to users during scheduled maintenance on the login page  and/or when there are critical update a maintenance page will display.

## Motivation and context ##
This is valuable to streamline the maintenance processes for Crossfeed. 

## Implementation notes ##

- Create/Edit/Delete Messages: Administrators can create, edit, and delete maintenance messages.
- Scheduled Messages: Ability to schedule messages for specific dates and times.
-  Display Messages: Messages are prominently displayed to users during maintenance periods.
-  Notification System: Optionally, provide a notification system for users to be informed about upcoming maintenance.

No active or inactive notifications screen
![image](https://github.com/cisagov/XFD/assets/19600787/3c65d05a-b102-456e-91d1-449435db7064)

Active notification and inactive notifications
![image](https://github.com/cisagov/XFD/assets/19600787/448a691c-2c57-4e50-928b-9c870c5cb9db)

Add New notification card and validation
![image](https://github.com/cisagov/XFD/assets/19600787/25237fbf-73d0-4ccd-8579-bba9cb3e4558)
![image](https://github.com/cisagov/XFD/assets/19600787/bc45ac36-9043-4195-b906-74f9f52eb69a)

Update notification pop up and validation
![image](https://github.com/cisagov/XFD/assets/19600787/e3f7f54e-f352-433e-8e64-74ba06019a81)
![image](https://github.com/cisagov/XFD/assets/19600787/afa06395-16a4-4c6c-ab5d-0df349ca1d58)

## Acceptance criteria ##

- [ ] Document all end-point changes
- [ ] Demonstrate a Response Design
- [ ] Include Screenshots Of Updated Views
- [ ] Commit to Staging
- [ ] Create Functional Tests

**Comment by ameliav** [comment]
Will go back to task #133 first but will jot down my notes on I think may be appropriate fields for a table that will need to be added to the database as well as back-end endpoints to update maintenance messages.

**Fields for a data table (to be vetted):**

- **Field name, data type, allowed fields (if applicable)**
- id, string
- maintenanceType, string, minor/major
- status, string, active/disabled
- updatedAt, date
- updatedBy, email
- message, string

Example data:

```
[
    {
        "id": 1,
        "maintenanceType": "minor",
        "status": "active",
        "updatedAt": "2024-03-26 21:34:17.304",
        "updatedBy": "jane.doe@test.com",
        "message": "Crossfeed has scheduled minor server maintenance on 3/28/2024 from 8:00AM to 5:00PM. Access to your Crossfeed settings will be limited. We apologize for the inconvenience. For further information, please reach out to admin@crossfeed.com."
    },
    { 
        "id": 2,
        "maintenanceType": "major",
        "status": "disabled",
        "updatedAt": "2024-03-26 21:34:17.304",
        "updatedBy": "john.doe@test.com",
        "message": "Crossfeed has scheduled major server maintenance from 3/28/2024 8:00AM to 3/29/2024 5:00PM. Access to Crossfeed will be disabled. We apologize for the inconvenience. For further information, please reach out to admin@crossfeed.com."
    }
  ]
```

**Comment by ameliav** [comment]
Designed a potential maintenance notifications interface. Need to know if this is going in the right direction, how many possible notifications there will be at a time, and what the exact fields to save should be.

<img width="1279" alt="image" src="https://github.com/cisagov/XFD/assets/19600787/b57b2336-79a3-4fd2-bea3-88ce650e637b">
