### ISSUE TITLE
DOCS: Scanning FAQs - Add WAS UserAgent

### ISSUE THREAD

**Issue by jennythompson8675309** [cisagov/XFD#101]
# 💡 Summary #

Add the UserAgent WAS uses to this page: https://docs.crossfeed.cyber.dhs.gov/scans/

## Motivation and context ##

Crossfeed will also offer reports of CyHy scans, so this page should include the WAS UserAgent as well as the current Crossfeed UserAgent.

## Implementation notes ##

Include this UserAgent for WAS:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Comment by jennythompson8675309** [comment]
Changes based on the rebranding of Crossfeed to the CyHy Dashboard:

Change this subtitle "What is Crossfeed?" to "The CyHy Dashboard is Powered by Crossfeed"

**Comment by schmelz21** [comment]
This is OBE. Scope has changed and no requirements were derived for the initial portion of this task.
