### ISSUE TITLE
DOCS: User Guide - Quickstart Updates

### ISSUE THREAD

**Issue by jthough9** [cisagov/XFD#104]
# 💡 Summary #

Requesting changes to the quickstart sections of the User Guide located here. https://docs.crossfeed.cyber.dhs.gov/user-guide/quickstart/ 

## Implementation notes ##

Please hide or remove these sections completely from the User Guide:
-Accepting an Invite
-Inviting Others
-Adding Root Domains
-Tailoring Data Sources

Can you please change the first paragraph of the Overview section to say:

"Once you are logged in, you can view an overview of your organization's domains and risk summary on the "Overview" panel. To list the available options, they are as follows:
[bullet point] Latest Vulnerabilities
[bullet point] Most Common Ports
[bullet point] Open Vulnerabilities by Domain
[bullet point] Severity Levels"

Can you please change the first paragraph of the Viewing Assets section to say:

"Standard users can search their own inventory in a variety of ways, including by IP(s), Domains(s), and associated vulnerabilities. Each search result represents a domain, which can have ports, products, and vulnerabilities associated with it."

Additionally can we add an arrow pointing to the search bar in the picture below this paragraph.

Lastly can please reduce the last paragraph in the viewing assets section to only say"

"Finally, you can click on a vulnerability to view more information, such as references to links and its history."

## Acceptance criteria ##

How do we know when this work is done?

- When all updates have been made to the User Guide Quickstart section and have been confirmed with either Nicole Q, Jennifer T, Mina S, or Jonathan H

**Comment by jennythompson8675309** [comment]
After implementation, the section should look like this (text revised to reflect rebranding from Crossfeed Platform to CyHy Dashboard):

### The CyHy Dashboard Product and Review  

The CyHy Dashboard is a web application with a self-service portal that collects and visualizes attack surface data from diverse sources to provide actionable information about organizational assets. The tool continuously enumerates and monitors an organization’s public-facing attack surface to discover assets and flag potential security flaws.  

## Features  

- Aggregates data from various public sources as well as performing custom enumeration techniques and indexing accessible services. All results are stored in a central database and made accessible for easy digestion. 
- Supports self-service functionality, where users can sign in with their own accounts and then obtain scan results. 
- Supports both passive and active scan types for organizations, which allows coordinating scans according to user comfort level. 
- Enables asset analysis and visualizations, as well as user-specific dashboards. 

## Use Cases 

With the CyHy Dashboard, an analyst can: 

- Access an interface that provides known assets and ability to discover new ones to ensure a thorough external attack surface monitoring 
- Utilize a map of the attack surface, providing a clear representation of all externally accessible assets. 
- Access a customizable dashboard that prioritizes vulnerabilities found through passive and active scanning, highlighting critical issues for real-time problems. 

## Design Details 

View our design details through our github located [here](https://github.com/cisagov/XFD?tab=readme-ov-file).

**Comment by jennythompson8675309** [comment]
Please change the text in the blue "Note" box to read:

### Note 

The CyHy Dashboard is powered by Crossfeed, which is developed as an open-source tool available on GitHub. The below instructions describe how users can use the CyHy Dashboard once enrolled. If you are a developer and want to set up your own Crossfeed instance, see [Creating your own instance of Crossfeed](https://docs.crossfeed.cyber.dhs.gov/dev/own-instance/).

**Comment by schmelz21** [comment]
This is OBE. Scope has changed and no requirements were derived for the initial portion of this task.
