### ISSUE TITLE
DOCS: User Guide - Crossfeed Product Overview Updates

### ISSUE THREAD

**Issue by jthough9** [cisagov/XFD#105]
# 💡 Summary #

Requesting changes to be made to the Crossfeed Product Overview section of the User Guide

## Implementation notes ##

Please hide or remove the Design Details section

Please change the introduction paragraph to the Crossfeed Product and Review to say:

"Crossfeed is a web application with a self-service portal that collects and visualizes attack surface data from diverse sources to provide actionable information about organizational assets. The tool continuously enumerates and monitors an organization's public-facing attack surface to discover assets and flag potential security flaws."

Please remove the "(Censys, Project Sonar, ect.)" portion of the first bullet point in the features section

Please delete the 2 Use Cases currently in the Use Case section and replace them with these 3 bullet points:

["Access an interface that provides known assets and ability to discover new ones to ensure a thorough external attack surface monitoring"

"Utilize a map of the attack surface, providing a clear representation of all externally accessible assets."

"Access a customizable dashboard that prioritizes vulnerabilities found through passive and active scanning, highlighting critical issues for real-time problems."]

Please delete everything in the Design Details section and replace it with:

"View our design details through our github located here." Then use "here" as a hyperlink to the Github page

## Acceptance criteria ##

How do we know when this work is done?

- When all updates have been made to the User Guide Quickstart section and have been confirmed with either Nicole Q, Jennifer T, Mina S, or Jonathan H

**Comment by jennythompson8675309** [comment]
After implementation, the section should look like this (text revised to reflect rebranding from Crossfeed Platform to CyHy Dashboard):

### The CyHy Dashboard Product and Review  

The CyHy Dashboard is a web application with a self-service portal that collects and visualizes attack surface data from diverse sources to provide actionable information about organizational assets. The tool continuously enumerates and monitors an organization’s public-facing attack surface to discover assets and flag potential security flaws.  

## Features  

- Aggregates data from various public sources as well as performing custom enumeration techniques and indexing accessible services. All results are stored in a central database and made accessible for easy digestion. 
- Supports self-service functionality, where users can sign in with their own accounts and then obtain scan results. 
- Supports both passive and active scan types for organizations, which allows coordinating scans according to user comfort level. 
- Enables asset analysis and visualizations, as well as user-specific dashboards. 

## Use Cases 

With the CyHy Dashboard, an analyst can: 

- Access an interface that provides known assets and ability to discover new ones to ensure a thorough external attack surface monitoring 
- Utilize a map of the attack surface, providing a clear representation of all externally accessible assets. 
- Access a customizable dashboard that prioritizes vulnerabilities found through passive and active scanning, highlighting critical issues for real-time problems. 

## Design Details 

View our design details through our github located [here](https://github.com/cisagov/XFD?tab=readme-ov-file).

**Comment by schmelz21** [comment]
This is OBE. Scope has changed and no requirements were derived for the initial portion of this task.
