### ISSUE TITLE
DOCS: User Guide - Administration Section Updates

### ISSUE THREAD

**Issue by jthough9** [cisagov/XFD#106]
# 💡 Summary #

Please hide the Administration section as a whole due to the fact this site will be used for a standard user as of now

## Motivation and context ##

Standard users can not perform Administration tasks

## Implementation notes ##

Please hide or delete the Administration section as a whole

## Acceptance criteria ##

How do we know when this work is done?

- When all updates have been made to the User Guide Quickstart section and have been confirmed with either Nicole Q, Jennifer T, Mina S, or Jonathan H

**Comment by jennythompson8675309** [comment]
The request to remove this section is not impacted by the rebranding of the Crossfeed Platform to the CyHy Dashboard. This issue can be implemented as requested.

**Comment by schmelz21** [comment]
This is OBE. Scope has changed and no requirements were derived for the initial portion of this task.
