### ISSUE TITLE
Resolve Lint Issues Flagged by GitHub Actions

### ISSUE THREAD

**Issue by Matthew-Grayson** [cisagov/XFD#13]
- [x] Revert .yamllint and .mdl_config.yaml changes in PR #5. (I am holding off on reverting .mdl_config.yaml but doing so is referenced in issue #79.)
- [x] Fix issues identified by each of the following pre-commit hooks:

General hooks

- [x] check-case-conflict
- [x] check-executables-have-shebangs
- [x] check-json
- [x] check-merge-conflict
- [x] check-toml (removed; N/A to project)
- [x] check-xml (removed; N/A to project)
- [x] debug-statements
- [x] detect-aws-credentials
- [x] detect-private-key
- [x] end-of-file-fixer
- [x] mixed-line-ending
- [x] pretty-format-json
- [x] requirements-txt-fixer
- [x] trailing-whitespace
  - Exclude test snapshots `exclude: .*.snap`
- [x] validate_manifest

Text file hooks
- [x] markdownlint
- [x] prettier
- [x] yamllint

Shell script hooks
- [x] shell-lint
- [x] shfmt

Python hooks
- [x] bandit
- [x] black
- [x] flake8
- [x] isort
- [x] mypy
- [x] pyupgrade

Terraform hooks
- [x] terraform_fmt
- [x] terraform_validate

Docker hooks
- [x] docker-compose-check

To setup pre-commit locally, run ./setup-env.
If it fails to run, follow the instructions returned in the console. This includes installing pyenv pyenv-virtualenv, and adding its path to .zhrc.

To run the check-case-conflict hook, run `pre-commit run check-case-conflict --all-files`.
To run a different hook, replace check-case-conflict with the name of the hook.

**Comment by Matthew-Grayson** [comment]
Per Fusion's recommendation via @michaelsaki, I am:

- Dividing this into separate issues,
- Reverting the rule sets found in .pre-commit-config.yaml, .yamllint, etc., and
- Coding exceptions to rules in individual files.

Reverting the rule sets will reduce Fusion's level of effort and turnaround time when reviewing lineage PRs.

**Comment by Matthew-Grayson** [comment]
See issues #26, #28, #29, #48, #77, #79, #91, and #92.

**Comment by schmelz21** [comment]
@Matthew-Grayson  - looks like we can close this ticket.

**Comment by Matthew-Grayson** [comment]
What a ride
