### ISSUE TITLE
Update Scan Page and Address Dependencies

### ISSUE THREAD

**Issue by schmelz21** [cisagov/XFD#133]
# 💡 Summary #

The current state of the project includes the “Web Page Scan” feature, which is considered out of scope for our project goals. Additionally, we need to ensure that all dependencies, especially related to routing, are properly addressed.

## Motivation and context ##

Eliminates confusion to the process to pull vulnerability data for organizations.

## Implementation notes ##

- Change Scans page to Admin Tools (Only “Global Admin” Accessible)
- Update header by moving link to right-left dropdown menu
- Add Administration tools for site maintenance to Admins Tools page
- Remove any other code dependencies

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Add simple screen shot to ticket for proof
- [ ] Ensure that all necessary dependencies are addressed
- [ ] Update Playwright Tests

**Comment by ameliav** [comment]
Dependencies:

1. CVE data is fetched locally through a scan (cveSync). Need a way to automatically load this data during the docker build if this data cannot be loaded afterwards.
2. Any other scans that were manual or scheduled through the UI must now be made in the backend.

@schmelz21

**Comment by schmelz21** [comment]
@aloftus23, @rapidray12 - scheduling a breakout session to discuss.
