### ISSUE TITLE
Create DigiCert for RSC

### ISSUE THREAD

**Issue by schmelz21** [cisagov/XFD#176]
# 💡 Summary #

Update DNS management

## Implementation notes ##

Please provide details for implementation, such as:

- Generate a Certificate Signing Request (CSR)
- send DigiCert a public key, identification and domain name

## Acceptance criteria ##

- [x] SSL certificate created

**Comment by cduhn17** [comment]
SSL cert for RSC has been created and sent along to Adam Joine
