### ISSUE TITLE
Update ReadySetCyber Footer Links

### ISSUE THREAD

**Issue by chrtorres** [cisagov/XFD#190]
# 💡 Summary #

Update ReadySetCyber Footer links to route correctly.

## Motivation and context ##

Currently, the links are filled with placeholders and do not route anywhere.

## Acceptance criteria ##

This issue would be closed once all the links are routed correctly.

- [x] Cisa Logo routes to Cisa.gov
- [x] All footer links route correctly

**Comment by michaelsaki** [comment]
This was resolved here: https://github.com/cisagov/XFD/pull/191
