### ISSUE TITLE
Proper routing for registration flow

### ISSUE THREAD

**Issue by michaelsaki** [cisagov/XFD#193]
# 💡 Summary #

We need to refine all the possible registration flows for an RSC user.

## Motivation and context ##

Currently there are some edge cases that haven't been fully developed for RSC.

For example: A registered RSC user is given a blank page when they attempt to access an XFD route. The user should be given a screen to redirect them back to RSC.

This will be considered an epic and broken up into multiple issues that will be linked to this until all of the **_main_** cases can be defined and fixed.

**Comment by hawkishpolicy** [comment]
Closing this issue as RSC Dashboard is no longer germane.
