### ISSUE TITLE
UAT for RSC Dashboard

### ISSUE THREAD

**Issue by michaelsaki** [cisagov/XFD#203]
# 💡 Summary #

RSC Dashboard needs to begin building out a user acceptance testing suite. Ideally the UAT will involve a full end to end testing environment from ServiceNow - RSC (Mission Instance) to XFD - RSC (RSC-Dashboard).

## Motivation and context ##

This was requested by leadership and will make it so we can ensure that the full RSC product is tested properly.

This epic will be broken out into smaller issues to be delivered over current and future iterations.

## Implementation notes ##

As of writing this issue we do not have any hard requirements so the following items are subject to change:

1. RSC Dashboard needs a "User Manual" to document the flows of registering an RSC user.
2. RSC Dashboard needs to build a test user. Ideally the test user would be the same user that makes a ServiceNow RSC assessment that then gets populated in the RSC Dashboard. This may involve working with Mission Instance to get the user working between both implementations of RSC.
3. UAT test plans need to be developed. Test Cases will need to be developed This might not necessarily need to be built out by the RSC Dashboard team. We will need to follow up on this with leadership.
4. Prepare the testing environment. It should mirror what production will look like. Mocked data will likely be used.
5. Manual UAT Sessions. There will need to be "Brown Bag" sessions hosted to show full end to end flows of RSC.

## Sub Issues ##
https://github.com/cisagov/XFD/issues/207

**Comment by hawkishpolicy** [comment]
Closing this issue as RSC Dashboard is no longer germane.
