### ISSUE TITLE
Optimize rscSync Fetch Requests

### ISSUE THREAD

**Issue by Matthew-Grayson** [cisagov/XFD#240]
# 💡 Summary #

Only pull assessments associated with an email address from mission instance. 

## Motivation and context ##

Reduces API response size by 65% in local testing.

## Implementation notes ##
For example
`.../api/now/table/x_g_dhs_rsc_rsc_data?sysparm_query=sys_updated_on>=${formattedDate}`
becomes
`.../api/now/table/x_g_dhs_rsc_rsc_data?sysparm_query=sys_updated_on>=${formattedDate}^u_contact_emailISNOTEMPTY`

**Comment by Matthew-Grayson** [comment]
Mission instance was purged on 10May2024. I'm unable to test the request until assessments are populated with a u_contact_email field.

**Comment by hawkishpolicy** [comment]
Closing this issue as RSC Dashboard is no longer germane.
