### ISSUE TITLE
UI: Adjust the Warning message not to overlay LOGIN.GOV button

### ISSUE THREAD

**Issue by schmelz21** [cisagov/XFD#328]
# 🐛 Summary #

When using a tablet or similar device with small screen resolution,  the Warning message at the bottom overlays on the LOGIN.COM button. This then blocks the User the ability to log in.

## To reproduce ##

1. Go to https://crossfeed.cyber.dhs.gov/
1. Then resize browser to a smaller size

## Expected behavior ##

We need the page to be more responsive for the User always able to access the LOGIN.GOV button.

![Screenshot 2024-06-06 at 10 34 35 AM](https://github.com/cisagov/XFD/assets/81192860/a5ecdb87-feb4-4712-9435-ae8b18ea7d4a)

**Comment by hawkishpolicy** [comment]
![Screenshot 2024-06-06 at 12 20 55 PM](https://github.com/cisagov/XFD/assets/123108455/2f2d9b0e-52a0-4270-a596-87d88a2a96d0)
![Screenshot 2024-06-06 at 12 21 06 PM](https://github.com/cisagov/XFD/assets/123108455/dc8a11a4-a784-4123-9687-7be4c3efb362)
![Screenshot 2024-06-06 at 12 21 14 PM](https://github.com/cisagov/XFD/assets/123108455/05e3751e-08fb-4698-a0cc-f46c5836a887)
