### ISSUE TITLE
Build Workflow Runs All Jobs Twice

### ISSUE THREAD

**Issue by Matthew-Grayson** [cisagov/XFD#34]
# 🐛 Summary #

Creating a PR initiates two instances of each build job. 'Run diagnostics' and 'lint' both run twice. These are spawned by .github/workflows/build.yml.

<img width="850" alt="Screenshot 2024-03-20 at 10 47 38" src="https://github.com/cisagov/XFD/assets/106278637/5fc4b552-5e82-4392-a71a-a60a2e6a50ea">

**Comment by schmelz21** [comment]
OBE - Verbally informed by CISA Development Team, there is no fix for this issue at the moment.
