### ISSUE TITLE
User CSV Import Not Functioning as Expected

### ISSUE THREAD

**Issue by aloftus23** [cisagov/XFD#40]
# 🐛 Summary #

I attached my CSV via the import file link but nothing happened.  And there's no button to proceed with import, or anything like that.  In fact, if I didn't hover of the import link, I would have had no indication the file was even uploaded :(

![image](https://github.com/cisagov/crossfeed/assets/33070478/c7136dd3-1ad5-4e25-87c4-8cfb9a68041a)

I suspect the import code was updated with the Oct2023 package because prior to the update, I had to convert the csv to xlsx for the UI to accept it.  Now it only sees csv.  

## To reproduce ##

- Log in and "export" the current users - This step is only needed to create a CSV file in the proper upload filename and format
- Edit the CSV file (remove the existing users and add the new ones)
- Import the edited file (DON'T change the file name - it's just safer that way - trust me)

## Expected behavior ##

I expected the Crossfeed to process the import file and add users - but nothing happened - nothing at all.

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

I captured this screenshot while working with @nickviola and @cduhn17:

![image](https://github.com/cisagov/crossfeed/assets/33070478/66761820-bd63-4ab3-8799-d531d84b9a60)

**Comment by schmelz21** [comment]
@aloftus23 - Can you confirm that the functionality to upload a list is working, there is just no UI/UX component for the User to understand the state of the upload. This may determine the priority of this bug.
