### ISSUE TITLE
Severity sort glitch CRASM-495

### ISSUE THREAD

**Issue by lwersiy** [cisagov/XFD#559]
# 🐛 Summary #

The current behavior in vulnerability sorting allows users to click the Severity sorting option multiple times, resulting in inconsistent sorting order.

## Expected behavior ##

Severity sorting option should consistently produce the same order even after multiple clicks

## Any helpful log output or screenshots ##

After first click
![Screenshot 2024-08-21 at 12 45 22 PM](https://github.com/user-attachments/assets/1ace662c-52d2-4a5f-a17b-6ae1c7b3f8f0)

After 2nd click
![Screenshot 2024-08-21 at 12 41 26 PM](https://github.com/user-attachments/assets/3e410576-621c-45ad-843c-bf8385e30643)

After 3rd click
![Screenshot 2024-08-21 at 12 51 02 PM](https://github.com/user-attachments/assets/9a7d4f6d-ce1a-4498-b72f-797686f96f6f)

**Comment by hawkishpolicy** [comment]
This can be closed.
