### ISSUE TITLE
Requesting information on updated steps for "Running Test" on Crossfeed User Guide (Development)

### ISSUE THREAD

**Issue by nikkq** [cisagov/XFD#69]
# 💡 Summary #

What is the work, as a high-level summary?  High Level summary. Requesting updated information for the following link: 
https://docs.crossfeed.cyber.dhs.gov/dev/quickstart/#running-tests

These steps will be for the latest User Guide development on Staging Crossfeed Documentation for Users.

Why does this work belong in this project?

This would be useful because ASM Solutions is required to provide the most accurate User Guide to CISA Leadership.

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?
New User Guide will be routed to leadership for approval. 

Please deliver updated steps to myself, Nicole Q. as I will revise and provide documentation to leadership.

**Comment by schmelz21** [comment]
OBE
