### ISSUE TITLE
Requesting information on updated steps for "Monitoring Docker Containers" on Crossfeed User Guide (Development)

### ISSUE THREAD

**Issue by nikkq** [cisagov/XFD#70]
# 💡 Summary #

What is the work, as a high-level summary? High Level summary. Requesting updated information for the following link: 
https://docs.crossfeed.cyber.dhs.gov/dev/quickstart/#monitoring-docker-containers 

## Motivation and context ##

Why does this work belong in this project? This would be useful because ASM Solutions is required to provide the most accurate User Guide to CISA Leadership.

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done? New User Guide will be routed to leadership for approval. 

Please deliver updated steps to myself, Nicole Q. as I will revise and provide documentation to leadership.

**Comment by nikkq** [comment]
Please submit latest updates to screenshots as well, if needed with updated information.

**Comment by schmelz21** [comment]
Closing issue as the steps to update this documentation is completed by developers. The following change request are being tracked: 
- https://github.com/cisagov/XFD/issues/106
- https://github.com/cisagov/XFD/issues/105
- https://github.com/cisagov/XFD/issues/101
- https://github.com/cisagov/XFD/issues/98
- https://github.com/cisagov/XFD/issues/81
