### ISSUE TITLE
Requesting information on updated steps for "Further Information" on Crossfeed User Guide (Development)

### ISSUE THREAD

**Issue by nikkq** [cisagov/XFD#72]
# 💡 Summary #

What is the work, as a high-level summary? High Level summary. Requesting updated information for the following link: 
https://docs.crossfeed.cyber.dhs.gov/dev/quickstart/#further-information

These steps will be for the latest User Guide development on Staging Crossfeed Documentation for Users.

## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done? New User Guide will be routed to leadership for approval. 

Please deliver updated steps to myself, Nicole Q. as I will revise and provide documentation to leadership.

- [ ] Criterion

**Comment by nikkq** [comment]
In addition, the links in the "further information" are no longer working. Requesting those be updated.

**Comment by schmelz21** [comment]
Closing issue as the steps to update this documentation is completed by developers. The following change request are being tracked: 
- https://github.com/cisagov/XFD/issues/106
- https://github.com/cisagov/XFD/issues/105
- https://github.com/cisagov/XFD/issues/101
- https://github.com/cisagov/XFD/issues/98
- https://github.com/cisagov/XFD/issues/81

**Comment by schmelz21** [comment]
This is OBE. Scope has changed and no requirements were derived for the initial portion of this task.
