### ISSUE TITLE
Remove Cloudwatch S3 bucket and lambda

### ISSUE THREAD

**Issue by aloftus23** [cisagov/XFD#80]
# 💡 Summary #

Remove Cloudwatch lambda and s3 bucket as it is no longer needed. 

## Motivation and context ##

No longer needed after realizing we can stream logs to Splunk straight from Cloudwatch.

## Implementation notes ##

Make sure there's no lingering resources.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by schmelz21** [comment]
This was completed - non repo issue.
