### ISSUE TITLE
DOCS: Development & API Reference - Remove these pages

### ISSUE THREAD

**Issue by jennythompson8675309** [cisagov/XFD#98]
# 💡 Summary #

Remove:
https://docs.crossfeed.cyber.dhs.gov/dev
https://docs.crossfeed.cyber.dhs.gov/api-reference/

## Motivation and context ##

Per Lamar, the audience for these two tabs is more technical than the intended audience for this site as a whole (ie standard external users). This information should still be available for developers, but keeping the info on github instead will be more efficient. 

## Implementation notes ##

- ensure all relevant information is available in github readmes, etc.
- remove those two pages from the docs site
- remove any internal references to those pages

**Comment by jennythompson8675309** [comment]
This change request is not impacted by the rebranding of Crossfeed to the CyHy Dashboard

**Comment by schmelz21** [comment]
This is OBE. Scope has changed and no requirements were derived for the initial portion of this task.
